### ISSUE TITLE
Profile Improvement: h265 Balanced

### ISSUE THREAD

**Issue by Cheezzhead** [Dictionarry-Hub/profilarr#131]
I was wondering why the 'x265' custom format is assigned a score of 0 in the '1080p h265 Balanced' quality profile, even though x265 implicitly means the release is in h265 format?

Looking at the [score breakdown](https://dictionarry.pages.dev/Profiles/1080p%20h265%20Balanced/) of this profile, I see 'x265' is listed under the `480p` section, which seems to imply (to me, at least) that this tag is only added to a release if it's in that resolution? But this is very clearly not true; many 1080p and even 4K releases that I come across are denoted by 'x265' and not 'h265'. As it stands, those releases will be rated below a release with the 'h264' tag (which has a score of +10), which seems.... counterintuitive, to say the least, for a profile specifically prioritising the HEVC format.

If I've misunderstood any part of the process, please correct me! But I've seen in practice on my Radarr and Sonarr installations that the h265 balanced profile seems to download h264 videos more often than not.

**Comment by santiagosayshey** [comment]
Hi there, the initial intention for this profile was to prioritise h265 only. h265 meaning lossless web-dls, not hevc encodes. This is why x265 is banned. The regex patterns are explicitly designed to determine whether these tags are used correctly. We have a FAQ on the discord that talks about this stuff if you're interested!

After lots of feedback, we decided to merge all hevc (lossless & encodes) into a single profile (hevc balanced). This new profile is still in testing, but is largely stable atm. It explicitly allows x265 encodes, if and only if it has been released by a reputable x265 encode group. You'll see that x265 is still given a negative score, but we inflate group scores to push scores back up. This way we remove bad x265 encodes, but still let the good ones through. In the next stable release, h265 balanced will be deprecated and replaced with this new profile. 

If you want to use this profile instead, you can clone the dev branch from this repo and import that way (as opposed to downloading the latest zip).

Hope that helps :) Let us know if you find this profile any better, any and all feedback is welcome!

**Comment by Cheezzhead** [comment]
Understood, I might give the dev branch a try, or otherwise wait for a stable release.

I will say, as someone who has *some* knowledge of release tagging (but by no means extensive), I have never known of this distinction between h265 and x265. To wit, the discord explicitly mentions:

- "This is the standard terminology we use for Dictionarry. It may be different elsewhere."; and
- "Disclaimer: Many HEVC files are mislabeled, making it challenging to distinguish between lossless and lossy releases based on release names alone."

Both of these make me, maybe not skeptical, but at the very least *hesitant* to adopt these as standards into my system (and I suspect I won't be alone in that). I don't yet know how the new hevc balanced profile will validate these rules. Or how much these rules are actually followed by the (notoriously decentralized) release groups. But for now changing the 'x265' custom filter to match the score of the 'h265' filter (+60) seems to be the best solution for my use-case.

**Comment by santiagosayshey** [comment]
@Cheezzhead 
> Both of these make me, perhaps not skeptical, but definitely _hesitant_ to adopt these as standard into my system - and I suspect I won't be alone in that.

Just to be clear, these standards are not Dictionarry exclusive. When I say "they may be different elsewhere", this mostly means singular releases on lower tier trackers. I use the same standards as PTP, BTN, HONE, etc. All use x265 to identify encodes and h265 to indicate lossless rips. Same for AVC - h264 for lossless rips, x264 for encodes. 

The profiles are specifically built around these standards to cover the majority of releases.
