### ISSUE TITLE
HTTP 400  syncing profiles with Sonarr

### ISSUE THREAD

**Issue by flamin-jellyfish** [Dictionarry-Hub/profilarr#136]
### Dictionarry Issue Report Format

**Title of Issue:** [Brief and descriptive title summarizing the issue]

**Description:**
[Provide a detailed description of the issue. Include what you were trying to achieve and what went wrong.]

**Environment:**
- **Operating System:** macOS Seqouia
- **Radarr/Sonarr Version:** 4.0.10.2544 Docker
- **Profilarr Version :** Latest

**Steps to Reproduce:**
1. Configure config.yaml
2. Run Syncarr or Updatarr.py
3. Select 2. Sonarr
4. Select any custom profile or all

**Expected Behavior:**
Profillar syncs custom profiles with sonarr.

**Actual Behavior:**
HTTP 400 error after syncing custom formats. Unable to sync profiles

**Screenshots/Logs:**
`Successfully added 0 custom formats, updated 138 custom formats.

Available profiles:
1. 1080p h265 Balanced  (sonarr - master).json
2. 1080p Optimal (Single Grab) (sonarr - master).json
3. 1080p Transparent (Double Grab) (sonarr - master).json
5. 2160p Optimal (Single Grab) (sonarr - master).json
6. 1080p Transparent (sonarr - master).json
7. 1080p Balanced (sonarr - master).json
8. 1080p Balanced (Single Grab) (sonarr - master).json
9. 2160p Optimal (sonarr - master).json
10. 1080p Optimal (sonarr - master).json
11. 1080p Transparent (Single Grab) (sonarr - master).json
12. 1080p h265 Balanced (Single Grab) (sonarr - master).json

Enter the numbers of the profiles you want to import separated by commas, or type 'all' to import all profiles: 
all
Importing Quality Profiles to sonarr : sonarr

HTTP Error 400.
Adding '1080p h265 Balanced ' quality profile : FAIL
HTTP Error 400.
Adding '1080p Optimal (Single Grab)' quality profile : FAIL
HTTP Error 400.
Adding '1080p Transparent (Double Grab)' quality profile : FAIL
HTTP Error 400.
Adding '2160p Optimal (Single Grab)' quality profile : FAIL
HTTP Error 400.
Adding '1080p Transparent' quality profile : FAIL
HTTP Error 400.
Adding '1080p Balanced' quality profile : FAIL
HTTP Error 400.
Adding '1080p Balanced (Single Grab)' quality profile : FAIL
HTTP Error 400.
Adding '2160p Optimal' quality profile : FAIL
HTTP Error 400.
Adding '1080p Optimal' quality profile : FAIL
HTTP Error 400.
Adding '1080p Transparent (Single Grab)' quality profile : FAIL
HTTP Error 400.
Adding '1080p h265 Balanced (Single Grab)' quality profile : FAIL
`

**Comment by santiagosayshey** [comment]
Known bug, happens due to a new quality added in Sonarr v4.0.10.2544.

I have exams for the next couple of weeks, so could be a while before I get around to fixing this

**Comment by mygrexit** [comment]
Am i missing something or is it just adding the quality to the profile @santiagosayshey?

```
        "quality": {
          "id": 22,
          "name": "Bluray-576p",
          "source": "bluray",
          "resolution": 576
        },
        "items": [],
        "allowed": false
      },
```
      
if its just that i could make a pr and you could approve it.
